name: country_codes
description: Country codes is an helper package that provides country details given a particular localization, such as dial codes, ISO 3166 codes (alpha-2, alpha-3) and country names.
version: 0.0.6+1
homepage: https://github.com/miguelpruivo/country_codes

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.miguelruivo.flutter.plugin.countrycodes.country_codes
    pluginClass: CountryCodesPlugin